// import './modal-movie-render';
import './api-service';
import './trailer.js';
import './popular-movies';
import './search-movies';
import './eventListeners';
import './modal-auth';
import './contributors-modal';
import './backdrop';
import './header';