import './api-service';
import './trailer';
import './popular-movies';
import './search-movies';
import './eventListeners';
import './modal-auth';
import './contributors-modal';
import './backdrop';
import './header';
import './modal-movie-render';
// import './range-slider';
import './filters';
// import './localstorage_movies';
import './add-filters-btn';
import './local-registration';
